name: Build linux-64-gmod artifact

on: [workflow_dispatch]

jobs:
  build-linux-gmod64:
    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - name: Install Dependencies
      run: |
        dpkg --add-architecture i386
        apt update
        apt install -y build-essential git libstdc++6:i386 gcc-multilib g++-multilib

    - name: Checkout Mini Source SDK
      uses: actions/checkout@v6
      with:
        repository: misyltoad/mini-source-sdk

    - name: Checkout VPhysics Jolt
      uses: actions/checkout@v6
      with:
        path: gmod/src/vphysics_jolt
        submodules: recursive

    - name: Build GCC x86_64
      working-directory: gmod/src
      run: |
        chmod +x createjoltprojects.sh
        chmod +x devtools/bin/vpc_linux
        chmod +x devtools/bin/vpc
        chmod +x devtools/gendbg.sh
        ./createjoltprojects.sh
        ARCH=x86_64 make -f jolt.mak -j $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: vphysics_jolt_gmod_linux64
        path: gmod/game
        if-no-files-found: error
